// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// estimating_function_first_order_mm
double estimating_function_first_order_mm(const arma::colvec& parameters, const arma::mat& data, const unsigned int model_dimension);
RcppExport SEXP dtwar_estimating_function_first_order_mm(SEXP parametersSEXP, SEXP dataSEXP, SEXP model_dimensionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type model_dimension(model_dimensionSEXP);
    rcpp_result_gen = Rcpp::wrap(estimating_function_first_order_mm(parameters, data, model_dimension));
    return rcpp_result_gen;
END_RCPP
}
// estimating_function_second_order_mm
arma::vec estimating_function_second_order_mm(const arma::colvec portfolio_allocation, const arma::mat sigma_star_matrix, const arma::mat m_matrix, const arma::mat data);
RcppExport SEXP dtwar_estimating_function_second_order_mm(SEXP portfolio_allocationSEXP, SEXP sigma_star_matrixSEXP, SEXP m_matrixSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type portfolio_allocation(portfolio_allocationSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type sigma_star_matrix(sigma_star_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type m_matrix(m_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(estimating_function_second_order_mm(portfolio_allocation, sigma_star_matrix, m_matrix, data));
    return rcpp_result_gen;
END_RCPP
}
// long_run_sigma
arma::mat long_run_sigma(arma::mat m_matrix, arma::mat sigma_star_matrix);
RcppExport SEXP dtwar_long_run_sigma(SEXP m_matrixSEXP, SEXP sigma_star_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m_matrix(m_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_star_matrix(sigma_star_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(long_run_sigma(m_matrix, sigma_star_matrix));
    return rcpp_result_gen;
END_RCPP
}
// war_prediction_and_residuals
List war_prediction_and_residuals(const arma::mat m_matrix, const arma::mat sigma_matrix, const arma::mat data);
RcppExport SEXP dtwar_war_prediction_and_residuals(SEXP m_matrixSEXP, SEXP sigma_matrixSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type m_matrix(m_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type sigma_matrix(sigma_matrixSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(war_prediction_and_residuals(m_matrix, sigma_matrix, data));
    return rcpp_result_gen;
END_RCPP
}
