# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimating_function_first_order_mm <- function(parameters, data, model_dimension) {
    .Call('dtwar_estimating_function_first_order_mm', PACKAGE = 'dtwar', parameters, data, model_dimension)
}

estimating_function_second_order_mm <- function(portfolio_allocation, sigma_star_matrix, m_matrix, data) {
    .Call('dtwar_estimating_function_second_order_mm', PACKAGE = 'dtwar', portfolio_allocation, sigma_star_matrix, m_matrix, data)
}

long_run_sigma <- function(m_matrix, sigma_star_matrix) {
    .Call('dtwar_long_run_sigma', PACKAGE = 'dtwar', m_matrix, sigma_star_matrix)
}

war_prediction_and_residuals <- function(m_matrix, sigma_matrix, data) {
    .Call('dtwar_war_prediction_and_residuals', PACKAGE = 'dtwar', m_matrix, sigma_matrix, data)
}

