# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimating_function_first_order_mm <- function(parameters, data, model_dimension) {
    .Call('dtwar_estimating_function_first_order_mm', PACKAGE = 'dtwar', parameters, data, model_dimension)
}

long_run_sigma <- function(m_matrix, sigma_star_matrix) {
    .Call('dtwar_long_run_sigma', PACKAGE = 'dtwar', m_matrix, sigma_star_matrix)
}

rcpparma_hello_world <- function() {
    .Call('dtwar_rcpparma_hello_world', PACKAGE = 'dtwar')
}

rcpparma_outerproduct <- function(x) {
    .Call('dtwar_rcpparma_outerproduct', PACKAGE = 'dtwar', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('dtwar_rcpparma_innerproduct', PACKAGE = 'dtwar', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('dtwar_rcpparma_bothproducts', PACKAGE = 'dtwar', x)
}

